### ISSUE TITLE
[PE-D][Tester D] Redundant example for tview command in UG 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-2/tp#199]
![Capture.PNG](https://raw.githubusercontent.com/shogun187/ped/main/files/7c370342-6386-48b2-a839-7de286125aec.PNG)

Perhaps the use of example is redundant if it is the same as the format

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: shogun187/ped#1

**Comment by lizekai-richard** [comment]
Not a bug
