### ISSUE TITLE
[PE-D][Tester B] Student ID Requirements are too strict

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W11-2/tp#201]
Student ID being forced to be nine characters long and starting and ending with a letter is okay in the context of NUS, which seems to be the target audience of this module.

However, perhaps consider removing this restriction, as it might be too strict.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Berted/ped#1

**Comment by leongdl135** [comment]
Interesting suggestion, however this is due to constraints of the product for NUS SOC professors.
