### ISSUE TITLE
[PE-D][Tester B] add: Consider making certain fields optional

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-2/tp#207]
Do professors usually keep track of student's phone number, telegram handle, and address? Perhaps such fields can be made optional.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Berted/ped#4

**Comment by leongdl135** [comment]
Interesting feature suggestion will be taken into consideration when doing future projects.
