### ISSUE TITLE
[PE-D][Tester D] Specific HH:MM time format for sadd not specified in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W11-2/tp#222]
Just a minor suggestion

Referring to your UG for the sadd command,

"The PERIOD includes the start time and the end time which are both in the format of the modern 24-hour clock."

This may be interpreted as an HHMM format, instead of the HH:MM which your application requires.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: shogun187/ped#7

**Comment by lizekai-richard** [comment]
Added specification in the UG!
