### ISSUE TITLE
[PE-D][Tester B] Color changes doesn't persist in timetable

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-2/tp#226]
We can click on the time periods to change colors in the timetable, however, the changes doesn't persist once we move screens.

![Animation.gif](https://raw.githubusercontent.com/Berted/ped/main/files/86b23ee6-ca50-4a83-8aeb-df878d132f4d.gif)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Berted/ped#7

**Comment by lizekai-richard** [comment]
This is one of the features of ProNUS. We want the timetable to be more colorful.

**Comment by lizekai-richard** [comment]
Not a bug
