### ISSUE TITLE
[PE-D][Tester D] seedit showing wrong error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-2/tp#228]
Perhaps as a follow up to the previous bug about seedit not working, if i change the index from 2 to 1, I get an unrelated error message saying the module doesnt exist, which was different from the other error. 
![seedit 2.PNG](https://raw.githubusercontent.com/shogun187/ped/main/files/ed12268a-9033-4a6c-96c2-d3785e772983.PNG)

![seedit 1.PNG](https://raw.githubusercontent.com/shogun187/ped/main/files/e395f8f2-e78d-4110-87ad-3197f1ccd931.PNG)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: shogun187/ped#9

**Comment by lizekai-richard** [comment]
This bug has been fixed.
