### ISSUE TITLE
[PE-D][Tester D] sdelete does not function properly

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-2/tp#230]
sdelete 2 does not work as shown in the screenshot, despite having a module at index 2.
![sdelete2.PNG](https://raw.githubusercontent.com/shogun187/ped/main/files/229ff0ab-e107-4f17-b16e-8af13d2fcb07.PNG)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: shogun187/ped#10

**Comment by lizekai-richard** [comment]
This bug has been fixed.
