### ISSUE TITLE
[PE-D][Tester D] tview does not function properly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W11-2/tp#234]
While in the schedule panel, if i input tview, the output does not change despite the command result displaying succesfully.

![tviewss.PNG](https://raw.githubusercontent.com/shogun187/ped/main/files/1fd58f3a-26ab-4937-9b82-84823374534a.PNG)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: shogun187/ped#11

**Comment by lizekai-richard** [comment]
Same issue as #235
