### ISSUE TITLE
[PE-D][Tester B] Scroll bar is invisible in dark mode

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W11-2/tp#237]
The timetable interface has a scroll pane, but it's not visible. Which can be problematic in the following scenario:

(small window size):

![image.png](https://raw.githubusercontent.com/Berted/ped/main/files/c6073946-5883-49df-ac62-9c3c63acd308.png)

(large window size):

![image.png](https://raw.githubusercontent.com/Berted/ped/main/files/3c10d83f-b37f-4f44-b6de-7e70e37452e0.png)

The schedule in 15:00-18:00 was hidden to the user. The indication of a scroll pane is not clear in dark mode. This is not an issue in light mode, see:

![image.png](https://raw.githubusercontent.com/Berted/ped/main/files/d21fa8d1-fd77-4ae8-98c3-bf1d85f827b7.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Berted/ped#10

**Comment by lizekai-richard** [comment]
Fixed
