### ISSUE TITLE
[PE-D][Tester B] Deleting Module Class doesn't delete respective data from TA and Students.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W11-2/tp#245]
When module class is deleted, the expected behaviour is for TA and Students to be unassigned from those modules immediately. However, this is not the case.

For instance, see the below possible module and student states

Current Module state:

![image.png](https://raw.githubusercontent.com/Berted/ped/main/files/7ddd7e10-1b40-42ca-a0c7-7022b5ca660c.png)

Current Student state:

![image.png](https://raw.githubusercontent.com/Berted/ped/main/files/ad49f42a-b9cd-44ea-9875-1066e2d6fcd3.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Berted/ped#11

**Comment by leongdl135** [comment]
Will fix bug in delete module command after integration.
