### ISSUE TITLE
Bug: schedule should use c/ prefix for module code instead of m/

### ISSUE THREAD

**Issue by bryanngzh** [AY2223S1-CS2103T-W11-2/tp#276]
1. Should remove `public static final Prefix PREFIX_MODULE_OF_SCHEDULE = new Prefix("m/");` and use ` public static final Prefix PREFIX_MODULE_CODE = new Prefix("c/");` in CliSyntax.java instead.
2. Update the use of prefixes for all schedule commands

**Comment by lizekai-richard** [comment]
Fixed
